services:
  - type: web
    name: hostel-token-booker
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium"
    startCommand: "gunicorn app:app --timeout 300 --workers 1"
    plan: free
